# Generated by Django 4.2.11 on 2024-05-07 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 5, 50, 45, 844254, tzinfo=datetime.timezone.utc)),
        ),
    ]
